<a href="https://colab.research.google.com/github/NamrathaBajjuri/AIML-TRAINING-TNSIF/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
uploaded =files.upload()

Saving weight-height.csv to weight-height.csv

In [4]:
df=pd.read_csv("weight-height.csv")
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [5]:
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [13]:
#Detect outliers using IQR
Q1 = df.Height.quantile(0.25)
Q3 = df.Height.quantile(0.75)
Q1, Q3

(np.float64(63.505620481218955), np.float64(69.1742617268347))

In [14]:
IQR = Q3 - Q1
IQR

np.float64(5.668641245615746)

In [15]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(np.float64(55.00265861279534), np.float64(77.67722359525831))

In [19]:
#Here are the outliers

df[(df.Height<lower_limit)|(df.Height>upper_limit)]

Empty DataFrame
Columns: [Gender, Height, Weight]
Index: []

In [23]:
# Calculate mean
mean_value = df['Height'].mean()

# Replace outliers with mean
df['Height'] = df['Height'].apply(
    lambda x: mean_value if x < lower_limit or x > upper_limit else x
)
# Print dataset
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [29]:
# Calculate median
median_value = df['Height'].median()

# Replace outliers with median
df['Height'] = df['Height'].apply(
    lambda x: median_value if x < lower_limit or x > upper_limit else x
)

# Print dataset
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [20]:
#Detect outliers using IQR
Q1 = df.Weight.quantile(0.25)
Q3 = df.Weight.quantile(0.75)
Q1, Q3

(np.float64(135.8180513055015), np.float64(187.16952486868348))

In [24]:
IQR = Q3 - Q1
IQR

np.float64(51.35147356318197)

In [25]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(np.float64(58.79084096072856), np.float64(264.19673521345646))

In [26]:
#Here are the outliers

df[(df.Weight<lower_limit)|(df.Weight>upper_limit)]

     Gender    Height      Weight
2014   Male  66.36756  269.989699

In [27]:
# Calculate mean
mean_value = df['Weight'].mean()

# Replace outliers with mean
df['Weight'] = df['Weight'].apply(
    lambda x: mean_value if x < lower_limit or x > upper_limit else x
)
# Print dataset
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [30]:
# Calculate median
median_value = df['Weight'].median()

# Replace outliers with median
df['Weight'] = df['Weight'].apply(
    lambda x: median_value if x < lower_limit or x > upper_limit else x
)

# Print dataset
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]